---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik-external
  namespace: &namespace networking
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 26.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image.tag: v3.0.0-beta5
    fullnameOverride: traefik-external
    deployment:
      kind: DaemonSet
      podLabels:
        app.kubernetes.io/service: {{ .Release.Name }}
    logs:
      general:
        level: DEBUG
        format: json
      access:
        enabled: true
        format: json
    ingressClass:
      enabled: true
      isDefaultClass: false
    ingressRoute:
      dashboard:
        enabled: false
    metrics:
      prometheus:
        entryPoint: metrics
        addRoutersLabels: true
    ports:
      metrics:
        expose: false
        exposedPort: 9100
        port: 9100
        protocol: TCP
      traefik:
        expose: false
        exposedPort: 9000
        port: 9000
        protocol: TCP
      web:
        expose: true
        exposedPort: 80
        port: 8000
        protocol: TCP
        redirectTo:
          port: websecure
      websecure:
        expose: true
        exposedPort: 443
        forwardedHeaders:
          insecure: false
        http3:
          enabled: true
        middlewares: []
        port: 8443
        protocol: TCP
        tls:
          certResolver: ""
          domains: []
          enabled: true
          options: ""
    providers:
      kubernetesCRD:
        allowCrossNamespace: false
        allowEmptyServices: false
        allowExternalNameServices: false
        enabled: true
        namespaces: []
      kubernetesIngress:
        allowEmptyServices: false
        allowExternalNameServices: false
        enabled: true
        namespaces: []
        publishedService:
          enabled: true
    service:
      enabled: true
      single: true
      spec:
        externalTrafficPolicy: Local
      type: LoadBalancer
