ansible_become_pass: ENC[AES256_GCM,data:DJlWiHt95zo8,iv:uCJ32q4KMuarQjMf+lmOJytaDZHl4xdCZx16gQpt8yA=,tag:ueeS1uD2HfKbmP2q3VWQYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ww3u7me5lwxtgqcd8djkv485q30wu7k40hs9e2acg8qvdw4e8spq9t5dem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrS1pwOC9SbEYvWW5LT054
            SmN6b0UwdUwrNzd1QlhMNVNZMG8rUTc5TWdFClV6WHphMm5Idjl3ckxBSzdObXpr
            NTROZHlkM0c5TW9IY3ZZODBvenlseEkKLS0tIG1JZWZpenQ1SWt0YlRpMWF2cm1Y
            NHNHQ0NGT3A0cXBFWUkvQ1lUWmNmb0UKIywB38Tj22XnIFR0A/nWOCZ3iFJjCX8y
            21c0sKZM0wOAuL7cnFmU6XSMuk7/D2A9tjsyb9eSb4ENjPwGuaRc1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T17:58:59Z"
    mac: ENC[AES256_GCM,data:kqoTczsl/RC+9FGv8A0tf9H8RuukBrT5g7v+iwH7bOSRBJRthdjzcl6w6++rmbJ0BjsrC5p3cCbiQmYxGoeH/vwn2sHjC6Et4MMNH0+T8D75WshYh6PwWxJvYvV+4FAMRkVvL4+P7eudMcSoZ2Bf23k6MyVP6l8mUUnfX8ACKXE=,iv:fzOIEkp0JY0es/Z4VSk386I93Otogf9uuss3ZSazUxg=,tag:2ziWpMqz6MeYqt77FQGUlA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
