ansible_become_pass: ENC[AES256_GCM,data:riieU2VTxKN6,iv:pVhhxFCX8uco3ECRuXu/xAZkkjRYZPPNugaSdtjUBFI=,tag:rG5EnNP8pvnh9ozHv/DzJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ww3u7me5lwxtgqcd8djkv485q30wu7k40hs9e2acg8qvdw4e8spq9t5dem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNHp0RWVZN3JJaGdyQkdl
            Ui9hcjh1WTVIK3pWTm9tLzg2dk92MTRPcmxJCjZYYnhpUk1ubE1iUDltc2pHUWNa
            cGhtUmo2MWN5NlZrckFUdi9zMmszT1UKLS0tIDZuMHZFR2tmR2tLRy90Qmpmb1J5
            OHRkQW9GUmhjQ1NkVDRQTDlYMzBxdVUK9S4FurCPNw8NBDwkAzFUg5G2setGUYqv
            Ce3MEmJXHAjrJspCodLt4i9bSIW/ajnZwTI2Yr8tA7VaSykkQbIk9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T15:47:49Z"
    mac: ENC[AES256_GCM,data:C+R0rQbA7AzH6g72HhprwL0ChIcgd+ziJksK4J/iLh20I2g17qfwH3vbJnIuKKVGhuXY2ZUh+pjJgNqWsV4vzx4LE2WXvELrhTFwIz5MMJA+5D4ATQkKkIGmFNswM+VUcQZQfP6Js4pfE6r0kRbsCPbBRmO1OG7I2uMxkh47R88=,iv:7SkT9afoMKMVKYV6mBANiwqL70rUt9fC4GcH+Sdt91A=,tag:lURs66s2vtUv2CbIUP/O/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
