ansible_become_pass: ENC[AES256_GCM,data:gh7BTw==,iv:iRIHB3cZ1HUomw+qt2xNjDT7h6osJNHwHdEFy+NGZLM=,tag:HfQ7FiZ8Gm//hlz+phrQJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ww3u7me5lwxtgqcd8djkv485q30wu7k40hs9e2acg8qvdw4e8spq9t5dem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydlZDRXhRQUhwYjIramU3
            bjNFZmRCV0NzbGdycllkVnFjcDUvWnJNckYwCmRhdjdMS0pSSmEyVEVhSHlJcUJB
            TVMzUkw3a1ZzZzF4N1FwVzlPVHZad2MKLS0tIGdreXFyLzhWeXhtSkVhdXRGRFJO
            UUNDQ2ZhZ1ZPbjRTTXJaekdCbzJjVncKdmOhlMV7w1xaCo7Me+F74L9JfKD4f21L
            Jf1Icc3smnMaJN/uzGUmA/LrxSAQNpQO69SjHBY70YPNx/X+KHHsKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T18:09:18Z"
    mac: ENC[AES256_GCM,data:5xxiPuR0HpGLwoAeAAkBi17y+aVpFt7EU00nmJQhTBfts+ZNlhDxzADGJ3sVhuZwD902k2CXpbgPvd06jNp5X/UmT2pd8CjILBLQswrIn5quMzDtFktIkdG3MXjm9HcQ9boAON9IcCHWX3JqQuNaaHyiQDhWIVo/NbeM76kQkbU=,iv:Uru5R/ar1ZvPOmdSILXzyZn+vX4x8Baj33cEeIn/1h8=,tag:f3VE6KGcNFeeUe4OdXqqSQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
