ansible_become_pass: ENC[AES256_GCM,data:xQ49kw==,iv:9U81ZtFbqTU6A5T4zbrY9UvVW5lFdELfcIHLljFo8tk=,tag:qL3a6eaNtKtaCvrViK1gBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ww3u7me5lwxtgqcd8djkv485q30wu7k40hs9e2acg8qvdw4e8spq9t5dem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLallRQm0wWXJMSEtmMmp1
            YWVzdFdYcGlzd085KzRTYVBiaXlOQXBCbWwwClRFQXc1ODFUY3FJUWIwYkRYU2VC
            OWZiSGdLT3d1cWxrRnJsTEtJSE56N2cKLS0tIHNhVjRBSTBTbW82L3NlMi9DeWdN
            aEN5M2grTEQwNlJtVGtvZVcxZUwvVFEKY9GC44/cXQkUdn5HMLzBWOIl2671FtZM
            wKhJ6Lvu2k/UAGGoEU4hZNHAEiUEOzEqQBAPfklILAANkLmjjyZguw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T18:09:18Z"
    mac: ENC[AES256_GCM,data:VXqkLkm2E4n9+QqwsMn36AkL3RM6cMv3uUkl58SJoFCTMjmco8mCL5Tob/h3qALYs+HeDCMdPFlYBre09qz4pghofsfFQSQSzT+INvXai69o/gZ3HHjS9aknYCAqneyEREzO/YYRDE2Vrn4zxaXLiuLFNtEN82mKCpj/6600d1A=,iv:YSciCRyGBKDNOpM3o1ee4HoQBz4hrY8yka7cxT9xZO0=,tag:0pk7vgcDYaNh+snMw59yOQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
