ansible_become_pass: ENC[AES256_GCM,data:l9iH0MeQCSM4,iv:GwPrYfAxelB51WJfDqsuVmdGtW+v0gMQ3q5ERTFuaBE=,tag:fYOx3UopR3AAfVyiEWa+Dw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ww3u7me5lwxtgqcd8djkv485q30wu7k40hs9e2acg8qvdw4e8spq9t5dem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaW14ZG5MZW1qT2h5bnZD
            VnpKcG8xMEYwUVpZWGZMWGJXMXNjazBGWG5vCk12Y0diWUQreGpmRStUZC93cnBi
            b0lyajZiZUlEWC8xRk9KeXVodGk5S0UKLS0tIElvdEtlczkraHQ2WTdlRTBBcVBr
            WVpmaUZNcHZkdmNqRDh1aEtFcndtdUEKyz5J9MUtjq3/135lC8leJ29N6WiQnMMo
            u/aa/VDHVXLNtwUK0EFkdxeWdXnaB2FkRzGF8csLa8AKhjeIypneqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T17:58:59Z"
    mac: ENC[AES256_GCM,data:I6FBwgmRYdx6ZHL+zqiW5L7AR4NYyoajiFb2vGa4VVdlIV5459v1esPJhwa778ZBEi8NFILES/Iij5BMy0YFtpKmu14JW3IExl22yxRX9iH5UqXMJx/3Du6BlpXjAVV4xAmEGFqy71SMEXRkmCb8M+/A4qmurEdTHclwOqNYh6Q=,iv:3eGY3OCkNfKn24SMpwBQ71O3cqHcgNGbNxeNByVBlZ8=,tag:J0j0iCGcgZ0Ft8aush5EtA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
