ansible_become_pass: ENC[AES256_GCM,data:DUj1JQ==,iv:oOUnWaQP/nvMYSxuAr/mDVDqlpdFt7s9Bi/5sutzSzo=,tag:nz6TfXkosWmFgtv/2GlFiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ww3u7me5lwxtgqcd8djkv485q30wu7k40hs9e2acg8qvdw4e8spq9t5dem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Sm9BajJpSFNzTE5MTDhu
            NzJmbDI2eERNcmNMa3pCenJuRGpLZGVFVHg4Cm16bUZMYkZvL3dIcFRLd2dyTER1
            Nnk1SWluQk1nYktnRDRzM1ZEV004V1UKLS0tIEt0bEVUNkpUM2dKdXprMXZKNXFr
            ZkowL1B4cmE4cTFzT3J3UWFBRlNGcTQK1nHzoQTsBjgXj8zyzLfW8mBAWiRRb+WT
            Ot/7UmoCCNteS6c5ER1bpa8lMrCq799ptDWaNH7r6gZznJRSGftcYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T18:09:18Z"
    mac: ENC[AES256_GCM,data:umamRINEzy/5OMeQ9ewdxDdWucNLAzG/vRbfUCif7WxOod/xElWJStMzOH8LR1+XTcoyqY5Yfv+fmLkqe9yVtcyZyziu4tmLepgGCuwCZwTdI/yHl1Aw4gLc1O0ujg48JZ1RxIfrghVYjO6QoEvz4Y29DpcL1595bx5JaW4XTqM=,iv:UZ1Bcxv/cQkhJj32G6afRZERD3bkbf1mWuV+Bxd5ZAI=,tag:uuBtmsOze6FBE7cHlsdVpA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
