---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./angelnu.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./csi-driver-nfs.yaml
  - ./datadog.yaml
  - ./democratic-csi.yaml
  - ./descheduler.yaml
  - ./external-dns.yaml
  - ./grafana.yaml
  - ./gpu-operator.yaml
  - ./hajimari.yaml
  - ./halkeye.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./kubernetes-sigs-nfd.yaml
  - ./metrics-server.yaml
  - ./piraeus.yaml
  - ./prometheus-community.yaml
  - ./rancher-latest.yaml
  - ./stakater.yaml
  - ./tailscale.yaml
  - ./traefik.yaml
  - ./weave-gitops.yaml
