apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:h0r7dV1VfBIIdqn08v/a0rz6DkvqJ+0S,iv:D5PR4A1dlMC8nJTN0Mzl3fjNFHr+cII/2AisP3FafbA=,tag:QLiR9MN1SqlO8+M/DSMDIA==,type:str]
    admin-user: ENC[AES256_GCM,data:cKqgRwY=,iv:qsHbGnmNw0/1rZPDbiU3VWvFRI69og7iu1FxpbCq1UQ=,tag:5CU8XnitAbqGDLvNKbKpHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ww3u7me5lwxtgqcd8djkv485q30wu7k40hs9e2acg8qvdw4e8spq9t5dem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcUt2YjVYUlc0L3hUOUsv
            MHVpVVRScEhNSGw1Ulp1ZExPbGVDU2JyU3pnCmtESDVHbXk4TVhpSE9IWmxOM2JC
            cEc4cWc2MWMvOVJ0Ty9aOTR0dXFEK2cKLS0tIHJ5WFhVeGtBZUpTcGdibWZHeDBJ
            MmpMN2Y5WnNGQWFoUHgvaEphc2tRQncKlBudF8NBWHaNd7WYWGMgwBzhDRuTMgCb
            i8uipn/4DPXOJgrQtt8rx2Wmv2HE91XoIcByMwBtaQySpSorV5xdQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T18:09:52Z"
    mac: ENC[AES256_GCM,data:x8DAVbm7r3TwHMVJlMLEi9V2724CIbguPx+gpGedWsqrkK8Lpfa1DyEsx7wThvxjjtTDOcJER7R4NPYnzNDcvJ+U/d3RB3qSJ237jEuZff00J3zAMhxHmKgeOz5w2BYlKHpewC3ZpgdtB3289ySsjyV7I1tsuXJYlFWGDJCJclI=,iv:xql6M+er5tBlBYQickymacsdQKMIN1yHKYWiPrsvvLk=,tag:hbmfnR1ujmbAfPvadZwyRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
