apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:YxnZPHcpbDdY,iv:8iTkb1hEvKBr1+iV6QeEohhBhRhKCsFjJcMluV3hpAw=,tag:+WIC8V1u5MXSxF4bBdlgiA==,type:str]
    admin-user: ENC[AES256_GCM,data:zQ0THEA=,iv:Xl8sk7q4U9byUWMEaDUCR11Twh6LcrAsJt6YbSVA4x4=,tag:7nrfggYLUxaM280YplExrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ww3u7me5lwxtgqcd8djkv485q30wu7k40hs9e2acg8qvdw4e8spq9t5dem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkV2hrcnpOWkNmUGFzN1BE
            aGx2MUdlUkN5SDd1QVpuY0NITlNtaEovaVhjCldGbE9LRk5oYVRMeVhoaUNFQ0dW
            MlRBYjgyQUdLNVFjUCtRbWpzcmQzUncKLS0tIFNidGFZNG8vaHNQU3dGeVRYc1Qv
            enJRVmw4c1Baa1R2RnJqdVBQWlg3NDAKnL0dt5AnmcT3WkrKEXShhaODDkRaiaX/
            yptrygX9LF26NepcL2KUKrXXGBqnuUM4bGPYSVLSqClK0VRjl0oQ4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T15:48:29Z"
    mac: ENC[AES256_GCM,data:n2PJ0iqNC1zhT7APDA6vAJUCI74keefNM/rPkjG8RPyeUwea+/wEfr0BTUFUhX4IstOeiBsXPb/3W5MK9JO8cxA/hUQZflDLkSb9Jj+fxreuJwDyqV/f5ILDbxl81Tnt94Sk6amvPZ3rF2fjgMx9RqApeVF0pXLxU6VpmmA8vM0=,iv:CzLSRb3kGNktXvMJ/F67FhwOLojdtJZwaFGBH8E4aRA=,tag:+yHwsI6Yr0zb9fqamwW7Sw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
