apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ww3u7me5lwxtgqcd8djkv485q30wu7k40hs9e2acg8qvdw4e8spq9t5dem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNVVldEpmem5nTXlwa0Nv
            eE5DWHg1TnhKVytaWVRIWDhzd2Z4YW85ZjJZCk1NUDFBb2dkOGs0V29kVVY2ZnQ0
            cHJadGdTRnovWUtmTGtpdVo2T0VwRHcKLS0tIGVra0RuS3JMeVdJc21zd3pydFY4
            TGMvOFpiS1VLckFvMWwyeVk1L0xrNGcK6viEPJ0pVAM8Z/iZyo+RqBSsPNgoBTds
            3tQl3NOoxO6y8DQhBqS5paYsJ4I5ftA+0Z9EBcasaiRCCBazxNHXBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T15:48:24Z"
    mac: ENC[AES256_GCM,data:UXewoC8lKI5qr4nDf8pYZhVEl1IIHxQ66DqMP1mpFEg+GjIgFijSLDRpZbQjOaBtf2b+lE44BlC5Q282kdYmYwfyyNXdPAPe7NwSUul7LG3ijieRcg9oeQbI0qiqoq4ztadSKh2WiL01peEl2bGgWsmGh9xekNrp56ahPcRL47c=,iv:v/HeAvIrOGUkooB20Jmg29XYToatFrSWKoFBdwoMMOA=,tag:2/C1/vy2V68WcpUAKdX5fA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
