apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ww3u7me5lwxtgqcd8djkv485q30wu7k40hs9e2acg8qvdw4e8spq9t5dem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeTg5c2ovT0FocjdydnhB
            T2Y5SGsrZ3M1UUQ5Qi9yRzVyUnJBbTBZY0hRCm16MFBHRitCWkljK2haOWNPamJJ
            QkRpbDJDRWhLdGtneFQ5b1NleFhESEEKLS0tIDFKczBjWWJXeWR2eTNtQzFGeFhM
            aHdOSU9PZWo0Y0hHV21MWjJFWTRDNEkKb1DCQKq5WV5iD8hohVdklJ0naY+ROxZ0
            YMkVAXrKhC5IVVbZgp1uZC/0Trd6PIPFsSuX6BgWNgBxwLBAA0Wy3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T17:59:29Z"
    mac: ENC[AES256_GCM,data:KWX2upwcNISi1sucB0wvg99gCJX0DENh5x8+DugB10bjLjQMB0feU6Jy+jR8KGrLydKaiS0IOUNUCElXWCVAvoJM6N3V83BOQAW5Vhu3eL+X2TbQ+7enK/fT1nhnceMzbkrXpfBA+VDiEcrYoH/n0t/SuHkptJZ2shB4UNUqq9c=,iv:kiIgX4sXubtRWBuV+YjF7XtCr3DBqeqOaYxTb2geIHU=,tag:wCJh/PWBweqMs0RoyWHuNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
