---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool-bgp-morpheus
spec:
  cidrs:
    - cidr: 172.16.8.0/24
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: policy-bgp-morpheus
spec:
  virtualRouters:
    - localASN: 65512
      neighbors:
        - peerASN: 65510
          peerAddress: 10.25.52.1/32
          gracefulRestart:
            enabled: true
            restartTimeSeconds: 120
      serviceSelector:
        matchExpressions:
          - {key: somekey, operator: NotIn, values: ['never-used-value']}
