---
timezone: "America/Chicago"
github_username: "bluevulpine"
coredns_addr: "10.43.0.10"
kube_vip_addr: "10.0.10.50"
cluster_cidr: "10.42.0.0/16"
service_cidr: "10.43.0.0/16"
node_cidr: "10.0.10.0/24"
cluster_cidr_v6: "fd78:c889:47fb:10::/60"
service_cidr_v6: "fd78:c889:47fb:e0::/112"
