---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: weave-gitops
spec:
  interval: 30m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.36
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    adminUser:
      create: true
      createSecret: false
      username: admin
    ingress:
    # tls.secretName breaks the helm chart for some reason
    # so the ingress is created manually below
      enabled: false
    networkPolicy:
      create: false
    metrics:
      enabled: true
    rbac:
      create: true
      impersonationResourceNames: ["admin"]
    podAnnotations:
      secret.reloader.stakater.com/reload: cluster-user-auth
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &name weave-gitops
  annotations:
    external-dns.alpha.kubernetes.io/target: "gitops.${SECRET_DOMAIN}"
    hajimari.io/icon: sawtooth-wave
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: traefik-internal
  rules:
  - host: &host "gitops.${SECRET_DOMAIN}"
    http:
      paths:
      - backend:
          service:
            name: *name
            port:
              number: 9001
        path: /
        pathType: Prefix
  hosts:
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: "weave-gitops-tls"
      hosts:
        - *host
