apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ouph6feIyzIaJdcRGlW6HyScE+uxczXLdjtBPaO8n9Q=,iv:2Si3yl7k58MRkOB6m5cK1klsIBfTtq7GnRKGFZzv0ys=,tag:/alzOukWAukCWMAOt25l2g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:sUZXOGOqZOouXYZlowH3whDB5yQ06VrxtB6wLJvUu1rjp8fh,iv:aDCPJcLudUrGssL/oG+K0CLabFZpgqMjqgDWjNCOhL0=,tag:2ML7fj1ImlaQH5fMx5dRZQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:GpAdxWUfRE61LGpFdU+Q,iv:nT7kk5vf6vU9rvuOeeS9jOZe4ifwPHa5IrtEh+3HsKc=,tag:Syp6RJBTt4vsNTNDz3rujg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ww3u7me5lwxtgqcd8djkv485q30wu7k40hs9e2acg8qvdw4e8spq9t5dem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcmVWVGxBVDZ2VFZFeXoy
            ZGRnbXFUZEZ4YnZySExnNnJGS3Fyb3hCMlVRClNhVCt4anFIb2RteGgzQjJnS2dZ
            SjlQaDNaYWUyY2ZXV1d6OWhJTzJhMmsKLS0tIHliRldnR1VBSnBrV3VrVEtlQ0hy
            NkJUR2FrQ2pkOEZFSXUxTzlXME1aSUUKBVEgPmbUxVMDRiIs7GtFjN4PHhp/cRFp
            G8sKcSGFhUOMVPd5yJIslWMuNkf5HvN+GEwqadJ9+BfoYOk0jenXtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T15:48:24Z"
    mac: ENC[AES256_GCM,data:C2eUfq9cFh6zNuWV8l32rouhoeYbRXbiC0Q25GVGQ6w1i3oikExCDXibqBZHScy7SSsRHpIS9niPvgAD7uG5WF1v85pGX1wWtZEn5wlouEEBepuhSqMc48oM0vRErwGyDGWkLPDsgUvXuaNGgw58yo+0nn+CG4HJEe7cGUFOucE=,iv:9yu3uRIMvdnAfnC/NrTHJjF1guBxT8GOJ7o8wsKhMXs=,tag:bKf9oqs2uOxZk11CAoaugA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
