apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:6OMQUTD0p7QkUnk7D1MCVsCLV/svFd+aXXeTUY038O//BviMBuld,iv:W86dJmUHcaMfPDsLkbeaREpQPnnQJxET9leeEiH/SXg=,tag:/XoErlKTaImFCiXOo1GRhg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:gx+EolGrkl8sfUjXlvTYDAFdhEPU9S59lFZlfw8nrwUycOtl,iv:ix6MmSWYcOeQxiZmbWQBumWrrbh/az7rdqM83zGZZFQ=,tag:FEB0jnRGh4EaxONnjMd3FQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:vOQfOoOc5MJTX+gCX6VZ,iv:J3F87E/dzsbJ1YJdwSbmtfu4lc/GA1A8BoGLz+miF6c=,tag:PZy0ya+khLUXf/75Dy8PvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ww3u7me5lwxtgqcd8djkv485q30wu7k40hs9e2acg8qvdw4e8spq9t5dem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUFpZWStRbmpOU2g2NXN5
            UzQ3bytNMUtyWk82UDd1UCtuMVZudUxldFJzCnVSM2FMKzh5MnN3eDJ4M3JUMmgz
            K0ExSDZNcmRVRXBvVTdOZ3VFbSttaHcKLS0tIGUvcDhWMTZEWHd2ZW5KMmdpQk91
            dGxBZE9adkIyZWxkQm9YcUQ5VEhBMXcKBnGY3govLKNYnhEaOEsZVu067EFEZmf4
            GqScRgJa6uxiFkd9R7lbS07hX4CcPh3HhzD0yGIg6QwGfHqrcQ8QIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T04:29:16Z"
    mac: ENC[AES256_GCM,data:Jagz+D+V2FPeAaDxIa/918Mg9JNzpl2z0wmeXKO8xsttAoYkQsdS26v3BO9QppHVwhl44r7QyaG70klBr0prczIryp5J5732b3HKdQSffn988b+LpXKf3q//ZAg0eNwnQT/8vSVCiuDtY7VRwENxZXBZu34W2iBB1l7uKRSjLWA=,iv:jKYuYrVvAhXjhnEW3WDiBqA4vjGTwYKbr8mL+P3Www0=,tag:2LYFFmSue2GyFiY8G/kSOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
