apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:mu/d8dO3VbCKEFWJIF3d8nE5PD1aJ25bMxAoWlPmgqo=,iv:9m+3jlpIiTSf/XgO+TQtSxlkTjc7c0XU1f+C0t/FuF8=,tag:rqJgC6/JVsUk/yLLTcpUrQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:rbMH1RhyvR4JXQCFwP8Fam3JbTekooJYPdttuXREs2vW/m4U,iv:ZWYnBLr/WfygfQpxMAPmx0wyeIz4BLST8x52lq6BpHs=,tag:EJoLXAjRzhhc1rS+6vbS/Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:omPAzeTweU81MwjtDB6J,iv:WC4gm+p5Y9D1kCzypNN4E6X//yGi6//cQtl6fHcP9sY=,tag:adqLCj/UZ1RH31viLROMBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ww3u7me5lwxtgqcd8djkv485q30wu7k40hs9e2acg8qvdw4e8spq9t5dem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocy9hSGgySThLVllDVXJv
            andFYmRCKy9oeUVXSy9TNE5EZkdvcnA0ekVNCjU0OWR5SXNnVEdoZ3l2QTJEelpV
            a0xvcWl2SUg2RzJWOFo1Z29teDBwK1kKLS0tIGhoTUJXVkxsT21wYkpWbEprWUJk
            eDFEc3liNnRnU0o3TGxhVlI1NTh5Z1kKynB9yYZloxyHnqa5pQvR/AqWqrTbrbtk
            RiQLSXh7tGVVua9Y9pErg73GEYYK4rw5nLpnx9Kw7JxYiLzm0hpbkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T18:09:48Z"
    mac: ENC[AES256_GCM,data:nYWfLJpHTH9nG+KO+CpPAv/IzQEcS6AikQ8Eq17Io5j0J3IjzcqLfpoOxBW8dMz3pKp4DM0sJ4R+ry8UEI/Ei/cZQsx9q0p7y/h9la94FHBLmayVjMTT5MGVx5ZCfi80cNBmPXRpcxZZ+Gnqx3yvVUBkJJqDmKk99N4a6pyFK2I=,iv:XqmrHWAWwD/bPRMPC8CS4marQ+/JTzHxjKTtD43jLbw=,tag:9U+jdbMkpxxfJxd6lD3m4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
