apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:pCUIqElsde//2LWT5mOB5qmMRJlrkRNONDnubb3S5+A=,iv:iYfgfp+OHDY5cAtRrSKqHr/5JE8rcGozBxJBOIOgu2o=,tag:WX0OmgHjiqlWqCnfjZhDKw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:glFKKxBRvA9nJXOGsyML+ytTVEwwNjh2FT2zBvVR1DcSBQ3O,iv:3om8vKjhh+jAXgXWPtKo5MtNHwd5QaZA5bPnBiO+apo=,tag:GSiMSDlv9GrefESglYSQpQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:abxOt41hjLG26CJcVLc7,iv:THyjpDQNC14u3pZ7bQF/qkY/UAC7+bdMUFjP2hv8ijg=,tag:OW2N0qlgI7bgU7x/BvgfDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ww3u7me5lwxtgqcd8djkv485q30wu7k40hs9e2acg8qvdw4e8spq9t5dem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRDNyU1NPYWQzRzJ2cFhr
            bWE5Tkt6bkZIMkowR2tuL042UjVRTVBiV1dBCk1rbmhTb045OCtnSVBUM2RXRnVz
            SzNxTjF3Zi9lU3RDTjFuR0crdzZqelkKLS0tIERKcWQwLzV4N1FCd2ZsdFc1L2hh
            YjJPSVMrQmZBcVFUaC8xWExXQVNsYmcKkInsHwP7XVCmofsDIUXEKA2Oov/BXRl/
            meo53yKXTOnD3vOVJShzV53q2K0JSnsdaaeEfHf42Yp7GsBe6NXNFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T17:59:29Z"
    mac: ENC[AES256_GCM,data:rl7vGv+nGGLu6jlLWPezuJEyZ+m8ofCyMt5TVv11JLIzy3AKVWFWR0BssR0RDfbAzNsKpYnJN1qlo7WVmxfLMUOsos3dOapcxjPoGHi6Zmu8YI5cIjNvRABBaSn8mRExiOjtjU9NlYh5nqKsJcAA87LUQLNQTsaXnysM1/cHttA=,iv:aDoRwDeSMNU5ukL33zAYS/RktuO+HWzZs0e9WwfxYgc=,tag:nBgtilCERXo6W1E+uSqUVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
