apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:2/nKwVYCCG319Ug05ylNu3jsE+Xh6RimaeJskllMzz63QMlR,iv:oRBC4uCZ6a65ktH1Qlp9vt5GTZluZf3VlOWF4a807aY=,tag:UIZrQlJv2nXG70Eq5cKB2Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:a3hBCC5p+ERN5FamoXCDIoxaJeXA31FL7+S6mtFn9OXuvP8DB7dSnzYLY5fKNmxjjsu5g2t8iMtVxT4yqFrm6DatkqH8Gzo96PZBo1tWDbobTX9ymQxzm4rLVZIMgbCb2h5g3Na+fCOP+RZakR9pW2slLea4yCF6bRYhKW7M4joCInrofgLYq7py56NM+1MSYtsx9r2wC6wTYKxsGL/KN1GvnPmsypgjetdV40XHLg==,iv:nKawTQhwkrvmvhQnVXw7kKRN8ex4XDaZBmmVKoNh72Q=,tag:LMlFQCBMG5qEqvP8BuTZTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ww3u7me5lwxtgqcd8djkv485q30wu7k40hs9e2acg8qvdw4e8spq9t5dem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT0VHR0ZnaGhsSDY5TXEv
            RENnMGVqanAxMHQxTk1jQkRLNnhNYmdtNm1vCkpJYVJPU25NMWdyUFpsUmU3OTRt
            VG1EQ3hHYjBPd2Vzc0d0SFVmOFlaVGcKLS0tIFgvcGg1WXphbkxvSnBmeEQ4bVdl
            eVdsZ2ZBeDQ0ajdXK3ZPbjdLZ28yVjgKeNZBGYjo17FxEB3YcGyPj6y+MtrkDSqW
            OXYweYmeklEMDFMxMCf0+eZHw3PjB9O07q0J/biYCwjrhwo6NN7E6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T17:59:29Z"
    mac: ENC[AES256_GCM,data:YuoJvFQpKWJLGeJeiebE4z8RJ6xb0WYK8nRbrRwW6yiKxl93wzssQLWn0iJRe1/ZknUJ8KjHyipXoYdik5mZDRgdMqs3c8q3lTkvFhyjJK3BYbE6zN9LmRSbw6FeiQES5O26/Hr1FqirgxUTTBDOruvzgDbqnt5ruAeH3gHQG+Q=,iv:78ww9DLYGQEYXa1kmOA57K1M2tUAmzNrS4l0+0/UVxM=,tag:WglUVxsgic2WToEVxUbyhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
