apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:QQ+B83/nNhBso4Kt5oXzMqKQxgsORi1V2hKv2WsVN0z9YHDc,iv:nV2EfA/1oN/yEvdm6NsEgnQYXqaP4M/MtUYxjiaVewk=,tag:llrj3d6OYbpP9oWMQFzFLA==,type:str]
    credentials.json: ENC[AES256_GCM,data:d/ugrqPwWAwHN2qpH6dJPt125lUjM9noZL675itutmtdVsQ2ldhv3UDICvOtaP78reuVs2lbszrkJanaPx6sMxlgCOmH6iWjOc/0qFu7O9N4krqADhRVaRz9lGtiIWqR4s8J+7Ojn+oqcxkyH4LKE4PhhYVxhdpSF17/AhU92Ic6FT4LOqzm+yjNCYH5YHF5ksV10Rptta0f1CnlEfypa+rFpST+KG60U1wKzA3juQ==,iv:bsKPf8IRiJoAgCGv0Cas7ROp/uyxs+LWl2JX8+V9zKU=,tag:M2U3nQ0bOM/zwsbu55fqSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ww3u7me5lwxtgqcd8djkv485q30wu7k40hs9e2acg8qvdw4e8spq9t5dem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZXBDaEwycHljMGx0czNr
            bXp3ZjBJdlhmU1l4NmNVa3VUdURURnZBWFR3CnhkWW5STy9xV1E0RS9RMmpzd2M4
            QU5rTXJJWDVwaXhiRFNtQk1oMjU2UlkKLS0tIGYwMVhacnZ4QTJ4WXphRnc3YlNN
            L213U3YwTmQwR2ZnTFN0aVRFZnlabHMKq4pfT9uEHOdAJN8RHpUqiuie1LSMu78l
            7lPewA/gSY4mCFHHIXIayZgJO4vMJpEUVXLit5YtqzDfo/3jQTLOog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T15:48:25Z"
    mac: ENC[AES256_GCM,data:9Gus99yHO6NXvr/dMwVqoqf4BXl7TO7FSO3K2EzBf6t9bNEWCBOEhiLrZ29c0EhhPzElExZBgTEuthUje23slw6hGybViBoJ2IwkvJA4nU3Ky98nmLz/w3j2eTsia/2ZUZ45zy6UIvQHhI4sWR9fh5jnoAmfbcIraBmwddnQMLk=,iv:i0DlQTvClcxnwKKB86xPM1A7Zv3zD2LoT6MZwTCFiWw=,tag:bfVxi1uhtwJn7yiS9IA5Jw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
